### PR TITLE
add build-pvector and make-pvector

### PR DESCRIPTION
**Pull request by AlexKnauth**
Does this implementation of `make-pvector` look sound to you? I might have misunderstood something or assumed something I shouldn't have.

### CODE REVIEW

**Comment by lexi-lambda** [comment]
This looks good. One thing: could you also implement `build-pvector` to be more clever? It could benefit from the same kind of fast implementation that `make-pvector` uses.

**Comment by AlexKnauth** [comment]
I would, but I don't really know how, and I don't think I know enough about how this data structure works to do it right. I was able to implement `make-pvector` that way because every element is the same, and so every node in a level is the same as every other node at that level, and I could structure the recursion around that. I don't know how to do that for something like `build-pvector`.

**Comment by lexi-lambda** [comment]
Ah, okay, that’s alright. I’ll try my hand at implementing `build-pvector` based on your `make-pvector` implementation. Thanks for working on this!

**Comment by lexi-lambda** [comment]
Merged in c0beb5ae5e6fba3e1c701d85881dc04ec4c8b733.

**Pull request closed without merging**
